name: sports_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  provider:  # provider
  fl_chart: ^0.70.2
  google_fonts:
  flutter_screenutil: 
  firebase_core:
  font_awesome_flutter:
  readmore:
  badges: # tages on cart etc
  animated_text_kit: # animeated text
  pin_code_fields: #pin code 
  firebase_auth: 
  cloud_firestore:
  firebase_storage:
  get:
  confetti:
  pinput:
  country_picker:
  geocoding:
  http:
  flutter_swiper_view:
  convex_bottom_bar:
  intl:
  flutter_svg:
  video_player:
  youtube_player_flutter:
  path_provider:
  change_app_package_name:
  reels_viewer:
  dio: 
  shared_preferences:
  get_it:
  device_info_plus:
  image_picker:
  logger:
  file_picker: 
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  timeago: ^3.2.2
  cached_network_image: ^3.4.1
  shimmer:
  modal_progress_hud_nsn:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/static_assets/
     - assets/dynamic_assets/
     - assets/icons_assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
